Docs in spanish
yiisoft/yii-cycle pull request #110
Opened 2021-10-13 18:15 UTC by AndreyPootMay

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |

In this pull-request I updated the docs for spanish documentation.

2021-10-29 22:52 UTC, terabytesoftw requested changes

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/README.md
> +Cycle es un motor PHP DataMapper ORM y de modelado de datos diseñado para trabajar con seguridad tanto en aplicaciones PHP clásicas como daemonizadas tales como [RoadRunner](https://github.com/spiral
```suggestion
Cycle es un motor PHP DataMapper ORM y de modelado de datos diseñado para trabajar tanto en aplicaciones PHP clásicas como daemonizadas tales como [RoadRunner](https://github.com/spiral/roadrunner).
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +`EntityReader` es una herramienta útil para transferir de forma segura las solicitudes de selección del repositorio al tiempo de ejecución del usuario.
```suggestion
`EntityReader` es una herramienta útil para transferir de forma segura las solicitudes de selección del repositorio en tiempo de ejecución del usuario.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +Una solicitud de selección se refiere a una instancia de uno de las clases: ``CycleORM\Select`` o ``Spiral\Database\Query\SelectQuery``.
```suggestion
Una solicitud de selección se refiere a una instancia de una de las clases: ``CycleORM\Select`` o ``Spiral\Database\Query\SelectQuery``.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +* Con `EntityReader` se puede ajustar la consulta de selección pasada:
```suggestion
* Con `EntityReader` se puede ajustar la consulta de selección:
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +  - Establezca `Limit` y `Offset` manualmente o con `OffsetPaginator`.
```suggestion
  - Establezca `Limit` y `Offset` manualmente con `OffsetPaginator`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +  - Establece la clasificación. Pero tenga en cuenta que la ordenación por `EntityReader` no sustituye la ordenación en la consulta original, sólo la complementa.Sin embargo, cada llamada posterior a
```suggestion
  - La ordenación por `EntityReader` no sustituye la ordenación en la consulta original, sólo la complementa. Sin embargo, cada llamada posterior al método `withSort()` sustituirá la configuración de clasificación del objeto `EntityReader`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +  - Aplicar filtro. Las condiciones del filtro `EntityReader` tampoco sustituyen al de filtrado en la consulta original, la complementan. Así, al filtrar en el objeto `EntityReader`, sólo puede refin
```suggestion
  - Las condiciones del filtro `EntityReader` tampoco sustituyen al de filtrado en la consulta original, solo la complementan. Así, que al filtrar el objeto `EntityReader`, sólo puede ajustar la selección pero no ampliarla.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +* Si utiliza los métodos `read()` y `readOne()` para leer los datos, entonces el `EntityReader` lo almacenará en una caché. El resultado de una llamada a `count()` también se almacena en caché.
```suggestion
* Si utiliza los métodos `read()` y `readOne()` para leer los datos, entonces `EntityReader` lo almacenará en una caché. El resultado de una llamada a `count()` también se almacena en caché.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +* Si no quieres que los datos se almacenen en caché, utiliza el método `getIterator()`.Sin embargo, si la caché ya está llena, `getIterator()` devolverá el contenido de la caché.
```suggestion
* Si no quieres que los datos se almacenen en caché, utiliza el método `getIterator()`. Sin embargo, si la caché ya está llena, `getIterator()` devolverá el contenido de la caché.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +Vamos a implementar un repositorio para trabajar con la tabla de artículos. Queremos un método para obtener artículos públicos `findPublic()` pero
```suggestion
Vamos a implementar un repositorio para trabajar con la tabla de artículos. Queremos un método para obtener artículos públicos `findPublic()`
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +Si necesitas establecer la ordenación por defecto en un método del repositorio pero quieres poder cambiarla en un controlador, puedes puede hacerlo de la siguiente manera:
```suggestion
Si necesitas establecer la ordenación por defecto en un método del repositorio, pero quieres poder cambiarla en un controlador, puedes puede hacerlo de la siguiente manera:
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/entity-reader.md
> +Puede refinar las condiciones de consulta con filtros. Estas condiciones de filtrado se añaden a las condiciones de consulta de selección originales, pero NO las sustituyen.
```suggestion
Puede ajustar las condiciones de consulta con filtros. Estas condiciones de filtrado se añaden a las condiciones de consulta de selección originales, pero no las sustituyen.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/installation.md
> +Si utiliza Yii con `composer-config-plugin`, la configuración de Yii-Cycle se puede especificar en `config/params.php`:
```suggestion
Si utiliza `yiisoft/config`, la configuración de `yisoft/yii-cycle` se debe especificar en `config/params.php`:
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Cycle ORM se basa en el esquema de la base de datos - objeto, que implementa la interfaz `\Cycle\ORM\SchemaInterface`.
```suggestion
Cycle ORM se basa en un esquema de base de datos, que implementa la interfaz `\Cycle\ORM\SchemaInterface`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Dado que un esquema se construye a partir de un array de una determinada estructura, podemos almacenarlo en caché o en un archivo de texto.
```suggestion
Dado que el esquema se construye a partir de un arreglo con una estructura definida, podemos almacenarlo en caché o en un archivo de texto.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +En el paquete `yii-cycle` el esquema puede ser construido desde múltiples fuentes representadas por múltiples proveedores que implementan
```suggestion
En el paquete `yiisoft/yii-cycle` el esquema puede ser construido desde múltiples fuentes representadas por múltiples proveedores que implementan
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Para utilizar varios proveedores de esquemas a su vez, se utiliza el proveedor `SchemaProviderPipeline` de agrupación.
```suggestion
Para utilizar varios proveedores de esquemas, se utiliza el proveedor `SchemaProviderPipeline` de agrupación.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Puede configurar este proveedor en la sección `schema-providers` de un archivo `config/params.php`.
```suggestion
Puede configurar este proveedor en la sección `schema-providers` en un archivo `config/params.php`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Organice los proveedores de esquemas en un orden tal, que los proveedores de caché estén al principio de la lista y los proveedores de esquemas de origen al final.
```suggestion
Los proveedores de esquemas deben estar organizados de la siguiente manera, los proveedores de caché deben estar al principio de la lista y los proveedores de esquemas de origen al final.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +`SchemaConveyorInterface`. Puede insertar sus propios generadores en este transportador definiéndolos en
```suggestion
`SchemaConveyorInterface`. Puede insertar sus propios generadores dentro del transpotador, para ello debe especificarlos en
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +`entity-paths` una opción del archivo `config/params.php`.
```suggestion
`entity-paths` dentro del archivo `config/params.php`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Colócalo al principio de la lista de proveedores para que el proceso de obtención de un esquema sea significativamente más rápido.
```suggestion
Debe indicarse al principio de la lista de proveedores para que el proceso de obtención de un esquema sea significativamente más rápido.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +1. `FromFilesSchemaProvider` carga un esquema desde archivos PHP a través de `include`. Esto requiere precauciones de seguridad.
```suggestion
1. `FromFilesSchemaProvider` carga un esquema desde un archivo `PHP` a través de `include`. Esto requiere precauciones de seguridad.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +2. Puede especificar varios archivos de esquema, que se fusionarán en un solo esquema.
```suggestion
2. Puede especificar varios archivos de esquema, los cuales se fusionarán en un solo esquema.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +3. Gracias a la caché interna, la carga del esquema desde un archivo PHP es tan rápida que puede omitirse por completo la caché externa.
```suggestion
3. Gracias a la caché interna, la carga del esquema desde un archivo `PHP` es tan rápida que puede omitirse por completo la caché externa.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Pero en el caso de que se carguen varios archivos, puede tardar más tiempo en fusionarlos.
```suggestion
En el caso de que se carguen varios archivos, puede tardar más tiempo en fusionase.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +4. No se pueden generar migraciones basadas en el esquema de archivos PHP. [Para más información mire el issue #25](https://github.com/yiisoft/yii-cycle/issues/25)
```suggestion
4. No se pueden generar migraciones basadas en el esquema de archivos `PHP`. [Para más información mire el issue #25](https://github.com/yiisoft/yii-cycle/issues/25)
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Para exportar el esquema como archivo PHP se puede utilizar el comando `cycle/schema/php`.
```suggestion
Para exportar el esquema como archivo `PHP` se puede utilizar el comando `cycle/schema/php`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Especifique un nombre de archivo como argumento y el esquema se escribirá en él:
```suggestion
Especifique el nombre del archivo como argumento y el esquema se escribirá en él:
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +Asegúrese de que el esquema exportado es correcto y luego pase a utilizarlo mediante `FromFilesSchemaProvider`.
```suggestion
Asegúrese de que el esquema exportado es correcto y luego puede utilizarlo mediante `FromFilesSchemaProvider`.
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +En el modo de lectura y escritura de un archivo de esquema, el proveedor `PhpFileSchemaProvider` funciona de forma similar a la caché, con
```suggestion
En el modo de lectura y escritura un archivo de esquema que utilice el proveedor `PhpFileSchemaProvider`, funcionara de forma similar a la caché, con
```

2021-10-29 22:52 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +la única diferencia es que el resultado guardado (archivo de esquema), puede ser guardado en codebase.
```suggestion
la única diferencia que el resultado guardado (archivo de esquema), puede ser guardado en codebase.
```

2021-10-29 23:03 UTC, terabytesoftw requested changes

2021-10-29 23:03 UTC, terabytesoftw commented on docs/es/reading-schema.md
> +A diferencia de `FromFilesSchemaProvider`, el `PhpFileSchemaProvider` trabaja con un solo archivo. pero, `PhpFileSchemaProvider`
```suggestion
A diferencia de `FromFilesSchemaProvider`, el archivo `PhpFileSchemaProvider` trabaja con un solo archivo de esquema `PhpFileSchemaProvider`
```

2021-11-02 20:56 UTC, AndreyPootMay commented
Ok, I'm going to change the files correctly, thanks :3

2021-12-23 23:25 UTC, merged

2021-12-23 23:27 UTC, terabytesoftw commented
👍