Increase coverage
yiisoft/yii-cycle pull request #201
Opened 2024-03-15 09:34 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-03-15 11:01 UTC, samdark commented on src/Command/Schema/SchemaPhpCommand.php
> +        }
Could be moved into `catch`.

2024-03-15 13:22 UTC, roxblnfk requested changes
The new code is not equivalent to the old one. I'm not sure if these changes are beneficial.

2024-03-18 13:52 UTC, vjik approved these changes

2024-03-18 15:26 UTC, roxblnfk approved these changes

2024-03-19 07:29 UTC, merged